# Generated by Django 5.2.17 on 2026-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
